# Generated by Django 5.0.6 on 2024-06-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('fullname', models.CharField(blank=True, help_text='Не обязательное поле', max_length=100, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('account_number', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Номер счета')),
                ('open_date', models.DateField(verbose_name='Дата открытия счета')),
                ('end_date', models.DateField(verbose_name='Дата окончания счета')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Дата фактического закрытия счета')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Текущий баланс')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='walletapp.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'Снятие'), ('TRANSFER', 'Перевод'), ('DEPOSIT', 'Пополнение')], max_length=10, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='walletapp.account', verbose_name='С какого счета')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='walletapp.account', verbose_name='На какой счет')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
